// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxvhlqxyyooueqlsyify.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4dmhscXh5eW9vdWVxbHN5aWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjMyNDgsImV4cCI6MjA3MDQ5OTI0OH0.lFCAXJxIJPgaDWfFi_gfwatF38R4WivYVB-oejavw20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});